services:
  client:
    build: ./client
    container_name: client
    networks:
      dnsnet:
        ipv4_address: 10.10.0.10

  resolver:
    build: ./resolver
    container_name: resolver
    environment:
      - PYTHONUNBUFFERED=1
      - UPSTREAM_DNS_IP=10.10.0.100
      - UPSTREAM_FIXED_SRC_PORT=33333
      - TXID_SPACE=1024
    networks:
      dnsnet:
        ipv4_address: 10.10.0.53

  auth:
    build: ./auth
    container_name: auth
    environment:
      - PYTHONUNBUFFERED=1
      - AUTH_DELAY_SECONDS=0.25
    networks:
      dnsnet:
        ipv4_address: 10.10.0.100

  attacker:
    build: ./attacker
    container_name: attacker
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      dnsnet:
        ipv4_address: 10.10.0.200

networks:
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
